### ISSUE TITLE
[PROVIDER] supernova.to

### ISSUE THREAD

**Issue by shinysocks** [mov-cli/mov-cli-films#4]
https://supernova.to

**Comment by r3tr0ananas** [comment]
So I checked it out and found two problems with it: firstly, I was being blocked when using a VPN, and secondly, I get no video.

**Comment by r3tr0ananas** [comment]
Okay i have found how to get links. 
![grafik](https://github.com/mov-cli/mov-cli-films/assets/132799819/bf76fc59-5c46-4ed2-b526-fc21ebd38a98)

But there is the VPN problem and i forgot about the cloudflare checking your browser.

**Comment by shinysocks** [comment]
yeah.. it might not work well as a provider, i'll close this
