### ISSUE TITLE
[Improvement] Use TMDb API

### ISSUE THREAD

**Issue by r3tr0ananas** [mov-cli/mov-cli-films#5]
@THEGOLDENPRO 

We would use the TMDb API instead of IMDb.

I know where we could get a API Key but just the API Key would originate from a streaming site.

**Comment by THEGOLDENPRO** [comment]
Why switch? Is it better?

**Comment by r3tr0ananas** [comment]
Yes, it would be much faster.

**Comment by r3tr0ananas** [comment]
and we can get extrametadata via the api, which in imdb we had to scrape.

**Comment by THEGOLDENPRO** [comment]
Oh cool, go ahead.

**Comment by r3tr0ananas** [comment]
I'll add it later.

**Comment by THEGOLDENPRO** [comment]
Oh my fucking god I see what you mean now. Try searching "mayday" and click on air crash investigation. 💀

*...it has 24 seasons*

**Comment by r3tr0ananas** [comment]
> Oh my fucking god I see what you mean now. Try searching "mayday" and click on air crash investigation. 💀
> 
> _...it has 24 seasons_

Try "Top Gear" it has 33 seasons.

**Comment by r3tr0ananas** [comment]
I am going to encode in base64, just in case they use something like [grep.app](https://grep.app/), so that they don't notice that we are using their key.

**Comment by r3tr0ananas** [comment]
TMDb has once again presented as with a problem, why do they have this shit.

![image](https://github.com/mov-cli/mov-cli-films/assets/132799819/96751195-3ede-46b4-bae7-96dca588a355)

![image](https://github.com/mov-cli/mov-cli-films/assets/132799819/b05d9745-a68c-472b-8fef-28184358b932)

**Comment by r3tr0ananas** [comment]
@THEGOLDENPRO

![image](https://github.com/mov-cli/mov-cli-films/assets/132799819/a2bdde27-ac7f-4fb6-80ec-5be0b7074fca)

this is how the serial would look like but i don't think we need something like vote_count, vote_average, video and so on

**Comment by THEGOLDENPRO** [comment]
What's that

**Comment by r3tr0ananas** [comment]
They split movies and tv shows.

**Comment by r3tr0ananas** [comment]
and this api is awful

**Comment by THEGOLDENPRO** [comment]
Why not scrape their site like last time

**Comment by r3tr0ananas** [comment]
it would be just slower.

**Comment by THEGOLDENPRO** [comment]
> it would be just slower.

Yeah but I think I would still be quicker than IMDb, I could be wrong but I remember tvmd displaying season/episode count much easier and quicker.

**Comment by r3tr0ananas** [comment]
https://github.com/mov-cli/mov-cli/tree/v4-tmdb-rewrite

**Comment by THEGOLDENPRO** [comment]
I think this has broken a couple of stuff.

**Comment by THEGOLDENPRO** [comment]
try searching for `mayday` once again 😂😭

**Comment by THEGOLDENPRO** [comment]
and they all seem to be 5 seasons with anything beyond season 1 returning media not found.

**Comment by THEGOLDENPRO** [comment]
I'm going to attempt to fix it.

**Comment by THEGOLDENPRO** [comment]
> try searching for `mayday` once again 😂😭

nevermind there just seems to be many films and tv shows called "mayday".
